# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_logo',
            field=models.FileField(default=b'settings.MEDIA_ROOT/media/abc.jpg', upload_to=b''),
        ),
    ]
