# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_picture_picture_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_logo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
