# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20170323_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flim_id', models.IntegerField(default=0)),
                ('flim_title', models.CharField(max_length=500)),
                ('pop_genres', models.CharField(max_length=1000)),
                ('pop_ratings', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pop_picture_logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
