# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='flim_id',
            new_name='film_id',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='flim_title',
            new_name='film_title',
        ),
    ]
